### ISSUE TITLE
server crashes 

### ISSUE THREAD

**Issue by OptfineTL** [DuckySoLucky/Vape-V4#19]
the python program crashes giving error 
Exception in callback BaseProactorEventLoop._start_serving.<locals>.loop(<_OverlappedF...56773, 0, 0))>) at C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.496.0_x64__qbz5n2kfra8p0\Lib\asyncio\proactor_events.py:840
handle: <Handle BaseProactorEventLoop._start_serving.<locals>.loop(<_OverlappedF...56773, 0, 0))>) at C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.496.0_x64__qbz5n2kfra8p0\Lib\asyncio\proactor_events.py:840>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.496.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 80, in _run    self._context.run(self._callback, *self._args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.496.0_x64__qbz5n2kfra8p0\Lib\asyncio\proactor_events.py", line 847, in loop
    protocol = protocol_factory()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websockets\server.py", line 103, in __init__
    super().__init__(**kwargs)
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websockets\protocol.py", line 235, in __init__
    self._drain_lock = asyncio.Lock(
                       ^^^^^^^^^^^^^
TypeError: Lock.__init__() got an unexpected keyword argument 'loop'

**Comment by OptfineTL** [comment]
issue resolved 
![image](https://user-images.githubusercontent.com/98396541/218265960-ba369313-619f-4f21-8c6f-25d332dd5284.png)

**Comment by OptfineTL** [comment]
issue resolved 
![image](https://user-images.githubusercontent.com/98396541/218265988-36a40513-35f6-4549-a934-7f9b1bfada5a.png)
