### ISSUE TITLE
Error while loading: unable to connect to server. if you can not resolve this issue please contact support

### ISSUE THREAD

**Issue by wowyourbad** [DuckySoLucky/Vape-V4#21]
I have followed all steps but when launching I get this
![Screenshot 2_12_2023 7_02_49 PM](https://user-images.githubusercontent.com/76994506/218325466-2c09dbca-490e-4c4d-8fe7-c38a536ee66b.png)

and this error: Exception in callback BaseProactorEventLoop._start_serving.<locals>.loop(<_OverlappedF...53935, 0, 0))>) at C:\Users\a\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py:818
handle: <Handle BaseProactorEventLoop._start_serving.<locals>.loop(<_OverlappedF...53935, 0, 0))>) at C:\Users\a\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py:818>
Traceback (most recent call last):
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 825, in loop
    protocol = protocol_factory()
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\server.py", line 103, in __init__
    super().__init__(**kwargs)
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\protocol.py", line 235, in __init__
    self._drain_lock = asyncio.Lock(
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\asyncio\locks.py", line 78, in __init__
    super().__init__(loop=loop)
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\asyncio\mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary

**Comment by wowyourbad** [comment]
and this error in a different window: 
Fail handler: websocketpp.transport.asio.socket:5 TLS handshake timed out
connection error 1
Fail handler: websocketpp.transport.asio.socket:5 TLS handshake timed out
connection error 2

**Comment by DuckySoLucky** [comment]
You need to use Python 3.9.0 version
