### ISSUE TITLE
python error 

### ISSUE THREAD

**Issue by Sexy-Frog** [DuckySoLucky/Vape-V4#4]
```
C:\Users\81904\Desktop\Vape-V4-main>py -3.9 server.py
Traceback (most recent call last):
  File "C:\Users\81904\Desktop\Vape-V4-main\server.py", line 8, in <module>
    import requests
  File "C:\Users\81904\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "C:\Users\81904\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\contrib\pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "C:\Users\81904\AppData\Local\Programs\Python\Python39\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "C:\Users\81904\AppData\Local\Programs\Python\Python39\lib\site-packages\OpenSSL\crypto.py", line 1556, in <module>
    class X509StoreFlags(object):
  File "C:\Users\81904\AppData\Local\Programs\Python\Python39\lib\site-packages\OpenSSL\crypto.py", line 1577, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```

how to fix this

**Comment by DuckySoLucky** [comment]
#3
