### ISSUE TITLE
how can i fix this

### ISSUE THREAD

**Issue by zerowaree** [DuckySoLucky/Vape-V4#40]
Exception in callback BaseProactorEventLoop._start_serving.<locals>.loop(<_OverlappedF... 3663, 0, 0))>) at C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py:840
handle: <Handle BaseProactorEventLoop._start_serving.<locals>.loop(<_OverlappedF... 3663, 0, 0))>) at C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py:840>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 847, in loop
    protocol = protocol_factory()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\server.py", line 103, in __init__
    super().__init__(**kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\protocol.py", line 235, in __init__
    self._drain_lock = asyncio.Lock(
                       ^^^^^^^^^^^^^
TypeError: Lock.__init__() got an unexpected keyword argument 'loop'

**Comment by DuckySoLucky** [comment]
You do not have correct python version installed. 

Contact me on Discord `DuckySoLucky#5181` if you need more help / faster response

**Comment by zerowaree** [comment]
Oh fuck i have 3.10 python xDDD im retarded
