### ISSUE TITLE
i cant open the vape v4

### ISSUE THREAD

**Issue by minh22421** [DuckySoLucky/Vape-V4#42]
i dk what is this:

Exception in callback BaseProactorEventLoop._start_serving.<locals>.loop(<_OverlappedF...55152, 0, 0))>) at C:\Users\-----\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py:836
handle: <Handle BaseProactorEventLoop._start_serving.<locals>.loop(<_OverlappedF...55152, 0, 0))>) at C:\Users\-----\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py:836>
Traceback (most recent call last):
  File "C:\Users\-----\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\-----\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 843, in loop
    protocol = protocol_factory()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\-----\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\server.py", line 103, in __init__
    super().__init__(**kwargs)
  File "C:\Users\-----\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\protocol.py", line 235, in __init__
    self._drain_lock = asyncio.Lock(
                       ^^^^^^^^^^^^^
TypeError: Lock.__init__() got an unexpected keyword argument 'loop'

**Comment by DuckySoLucky** [comment]
You do not have correct Python version, you need Python 3.9.0
